insert into states (id, title, code) values (1, 'Pennsylvania', '18706');
insert into states (id, title, code) values (2, 'Illinois', '62718');
insert into states (id, title, code) values (3, 'Iowa', '52245');
insert into states (id, title, code) values (4, 'New Mexico', '87195');
insert into states (id, title, code) values (5, 'Hawaii', '96835');
insert into states (id, title, code) values (6, 'California', '95173');
insert into states (id, title, code) values (7, 'Arizona', '86305');
insert into states (id, title, code) values (8, 'Texas', '79116');
insert into states (id, title, code) values (9, 'North Carolina', '28247');
insert into states (id, title, code) values (10, 'Florida', '33742');
insert into states (id, title, code) values (11, 'Washington', '98411');
insert into states (id, title, code) values (12, 'Georgia', '30392');
insert into states (id, title, code) values (13, 'California', '94169');
insert into states (id, title, code) values (14, 'Arizona', '85045');
insert into states (id, title, code) values (15, 'Texas', '79940');
insert into states (id, title, code) values (16, 'New York', '10557');
insert into states (id, title, code) values (17, 'Texas', '78754');
insert into states (id, title, code) values (18, 'Washington', '99252');
insert into states (id, title, code) values (19, 'Missouri', '65105');
insert into states (id, title, code) values (20, 'Missouri', '65110');
insert into states (id, title, code) values (21, 'District of Columbia', '20535');
insert into states (id, title, code) values (22, 'Nebraska', '68517');
insert into states (id, title, code) values (23, 'New York', '10045');
insert into states (id, title, code) values (24, 'Kentucky', '40298');
insert into states (id, title, code) values (25, 'District of Columbia', '20525');
insert into states (id, title, code) values (26, 'North Carolina', '28242');
insert into states (id, title, code) values (27, 'Virginia', '23663');
insert into states (id, title, code) values (28, 'New Jersey', '07104');
insert into states (id, title, code) values (29, 'Texas', '88525');
insert into states (id, title, code) values (30, 'California', '95354');
insert into states (id, title, code) values (31, 'Missouri', '64153');
insert into states (id, title, code) values (32, 'Nevada', '89120');
insert into states (id, title, code) values (33, 'Florida', '33283');
insert into states (id, title, code) values (34, 'Kentucky', '40215');
insert into states (id, title, code) values (35, 'New York', '11236');
insert into states (id, title, code) values (36, 'Pennsylvania', '16565');
insert into states (id, title, code) values (37, 'Texas', '78278');
insert into states (id, title, code) values (38, 'Texas', '75062');
insert into states (id, title, code) values (39, 'Texas', '76205');
insert into states (id, title, code) values (40, 'Florida', '33134');
insert into states (id, title, code) values (41, 'Nevada', '89135');
insert into states (id, title, code) values (42, 'Louisiana', '70883');
insert into states (id, title, code) values (43, 'Kansas', '66642');
insert into states (id, title, code) values (44, 'Oregon', '97306');
insert into states (id, title, code) values (45, 'Nebraska', '68110');
insert into states (id, title, code) values (46, 'Florida', '32123');
insert into states (id, title, code) values (47, 'Arkansas', '72215');
insert into states (id, title, code) values (48, 'Minnesota', '55470');
insert into states (id, title, code) values (49, 'Iowa', '52410');
insert into states (id, title, code) values (50, 'Missouri', '63116');
insert into states (id, title, code) values (51, 'Florida', '34745');
insert into states (id, title, code) values (52, 'New York', '10060');
insert into states (id, title, code) values (53, 'Florida', '33686');
insert into states (id, title, code) values (54, 'Texas', '77705');
insert into states (id, title, code) values (55, 'Texas', '77713');
insert into states (id, title, code) values (56, 'Texas', '76705');
insert into states (id, title, code) values (57, 'Nebraska', '68531');
insert into states (id, title, code) values (58, 'Utah', '84145');
insert into states (id, title, code) values (59, 'Texas', '88579');
insert into states (id, title, code) values (60, 'California', '91109');
insert into states (id, title, code) values (61, 'District of Columbia', '20520');
insert into states (id, title, code) values (62, 'Maryland', '21216');
insert into states (id, title, code) values (63, 'Wisconsin', '54313');
insert into states (id, title, code) values (64, 'Florida', '32225');
insert into states (id, title, code) values (65, 'Iowa', '50330');
insert into states (id, title, code) values (66, 'Missouri', '63136');
insert into states (id, title, code) values (67, 'New York', '13505');
insert into states (id, title, code) values (68, 'Florida', '33647');
insert into states (id, title, code) values (69, 'Kansas', '67205');
insert into states (id, title, code) values (70, 'Arizona', '85754');
insert into states (id, title, code) values (71, 'District of Columbia', '20430');
insert into states (id, title, code) values (72, 'California', '92056');
insert into states (id, title, code) values (73, 'California', '90035');
insert into states (id, title, code) values (74, 'Florida', '32128');
insert into states (id, title, code) values (75, 'North Carolina', '28405');
insert into states (id, title, code) values (76, 'Ohio', '44710');
insert into states (id, title, code) values (77, 'Ohio', '44315');
insert into states (id, title, code) values (78, 'New York', '10019');
insert into states (id, title, code) values (79, 'Massachusetts', '02208');
insert into states (id, title, code) values (80, 'Florida', '32969');
